export const generateClassReportHTML = (classData) => {
  const { className, term, year, stats, rankings } = classData;

  // Header and static info from image_2.png
  const schoolName = "TASSIA SCHOOL";
  const schoolMotto = '"Quest for Quality"';
  const schoolContact = "P.O Box 35235-00200, Nairobi | Tel: +254 020 82 0017, Cellphone: 0722 803 400";
  const generatedFooter = "Generated by EduManage Pro | Tassia School";

  // Create table rows for student rankings
  const rankingRows = rankings.map((student, index) => {
    // Add gold/silver/bronze stars for top 3
    const rankDisplay = index < 3 
      ? `<span class="star rank-${index + 1}">★</span>${index + 1}` 
      : index + 1;
    
    return `
      <tr>
        <td class="text-center font-bold">${rankDisplay}</td>
        <td>${student.name}</td>
        <td class="text-center">${student.mat}</td>
        <td class="text-center">${student.eng}</td>
        <td class="text-center">${student.kis}</td>
        <td class="text-center">${student.int}</td>
        <td class="text-center">${student.cre}</td>
        <td class="text-center">${student.pre}</td>
        <td class="text-center">${student.soc}</td>
        <td class="text-center">${student.rel}</td>
        <td class="text-center font-bold">${student.total}</td>
        <td class="text-center font-bold bg-highlight">${student.avg}%</td>
      </tr>
    `;
  }).join('');

  // The full HTML/CSS document
  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Class Report - ${className}</title>
      <style>
        body { font-family: sans-serif; padding: 20px; font-size: 13px; line-height: 1.4; color: #111; }
        .center { text-align: center; }
        .font-bold { font-weight: bold; }
        .divider { border-bottom: 2px solid black; margin: 10px 0; }
        .report-form { padding: 40px; border: 1px solid #ccc; max-width: 850px; margin: 0 auto; background: white; }
        
        /* Header from image */
        .header h1 { margin: 0; font-size: 24px; font-weight: bold; }
        .motto { font-style: italic; margin: 2px 0; font-size: 12px; color: #555; }
        .contact { font-size: 11px; margin: 2px 0; color: #777; }
        .form-title { font-weight: bold; font-size: 18px; text-decoration: underline; margin: 15px 0; }
        
        .meta-info { margin-bottom: 20px; text-transform: lowercase; color: #333; }

        /* Stats Cards from image_2.png */
        .stats-grid { display: flex; justify-content: space-between; gap: 15px; margin-bottom: 30px; }
        .stat-card { flex: 1; border: 1px solid #000; padding: 15px; text-align: center; background: #fff; }
        .stat-title { font-size: 10px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; color: #111; margin-bottom: 8px; }
        .stat-value { font-size: 24px; font-weight: bold; color: #111; }
        .stat-sub { font-size: 11px; color: #666; text-transform: lowercase; }

        /* Grade Table from image */
        table { width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 12px; }
        table, th, td { border: 1px solid #000; }
        th { background-color: #f3f4f6; font-weight: bold; font-size: 11px; text-transform: uppercase; color: #111; padding: 10px 5px; }
        td { padding: 8px 5px; color: #333; }
        .text-center { text-align: center; }
        .bg-highlight { background-color: #fff9db; }
        
        /* Star colors from image */
        .star { margin-right: 3px; font-size: 14px; }
        .rank-1 { color: #fcc419; } /* Gold */
        .rank-2 { color: #adb5bd; } /* Silver */
        .rank-3 { color: #e67700; } /* Bronze */

        .footer { text-align: center; margin-top: 40px; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 15px; }

        /* Print formatting */
        @media print {
          body { padding: 0; background: white; }
          .report-form { border: none; padding: 0; max-width: 100%; width: 100%; box-shadow: none; }
          .no-print { display: none; }
          th { -webkit-print-color-adjust: exact; background-color: #f3f4f6 !important; color-adjust: exact; }
          .bg-highlight { -webkit-print-color-adjust: exact; background-color: #fff9db !important; color-adjust: exact; }
          .stat-card { -webkit-print-color-adjust: exact; border: 1px solid #000 !important; color-adjust: exact; }
        }
      </style>
    </head>
    <body>
      <div class="report-form">
        <div class="header center">
          <h1>${schoolName}</h1>
          <p class="motto">${schoolMotto}</p>
          <p class="contact">${schoolContact}</p>
        </div>
        <div class="divider"></div>
        <div class="center form-title">GRADE PERFORMANCE REPORT</div>
        
        <div class="meta-info center">
          ${className} | END TERM 1 ${year} | ${year}
        </div>

        <div class="stats-grid">
          <div class="stat-card">
            <div class="stat-title">Average Score</div>
            <div class="stat-value">${stats.averageScore}%</div>
          </div>
          <div class="stat-card">
            <div class="stat-title">Pass Rate</div>
            <div class="stat-value">${stats.passRate}%</div>
          </div>
          <div class="stat-card">
            <div class="stat-title">Top Performer</div>
            <div class="stat-value" style="font-size: 16px; margin-top: 8px;">${stats.topPerformer}</div>
          </div>
          <div class="stat-card">
            <div class="stat-title">Lowest Subject</div>
            <div class="stat-value" style="font-size: 16px; margin-top: 8px;">${stats.lowestSubject.name}</div>
            <div class="stat-sub">(${stats.lowestSubject.avg}%)</div>
          </div>
        </div>

        <table>
          <thead>
            <tr>
              <th class="text-center" style="width: 50px;">Rank</th>
              <th style="width: 150px;">Student Name</th>
              <th class="text-center">Mat</th>
              <th class="text-center">Eng</th>
              <th class="text-center">Kis</th>
              <th class="text-center">Int</th>
              <th class="text-center">Cre</th>
              <th class="text-center">Pre</th>
              <th class="text-center">Soc</th>
              <th class="text-center">Rel</th>
              <th class="text-center" style="width: 60px;">Total</th>
              <th class="text-center" style="width: 60px;">Avg %</th>
            </tr>
          </thead>
          <tbody>
            ${rankingRows}
          </tbody>
        </table>

        <div class="footer">
          ${generatedFooter}
        </div>
      </div>
    </body>
    </html>
  `;
};